/*---------------------------------------------------------------------------*\
 ##   ####  ######     |
 ##  ##     ##         | Copyright: ICE Stroemungsfoschungs GmbH
 ##  ##     ####       |
 ##  ##     ##         | http://www.ice-sf.at
 ##   ####  ######     |
-------------------------------------------------------------------------------
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 1991-2008 OpenCFD Ltd.
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is based on OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Class
    Foam::dimensionedSphericalTensorEntryToExpression

Description
    Creates an expression from a dimensioned sphericalTensor

SourceFiles
    dimensionedSphericalTensorEntryToExpression.C

Contributors/Copyright:
    2014 Bernhard F.W. Gschaider <bgschaid@hfd-research.com>

 SWAK Revision: $Id$
\*---------------------------------------------------------------------------*/

#ifndef dimensionedSphericalTensorEntryToExpression_H
#define dimensionedSphericalTensorEntryToExpression_H

#include "entryToExpression.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                           Class dimensionedSphericalTensorEntryToExpression Declaration
\*---------------------------------------------------------------------------*/

class dimensionedSphericalTensorEntryToExpression
:
    public entryToExpression
{
    // Private data

    //- Construct as copy
    dimensionedSphericalTensorEntryToExpression(const dimensionedSphericalTensorEntryToExpression&);

    void operator=(const dimensionedSphericalTensorEntryToExpression&);

public:
    //- Runtime type information
    TypeName("dimensionedSphericalTensorEntryToExpression");

    // Constructors

    //- Construct null
    dimensionedSphericalTensorEntryToExpression();

    // Destructor

    virtual ~dimensionedSphericalTensorEntryToExpression();

    virtual string toExpr(const entry &);
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
