#! /bin/bash

if [ -e swakConfiguration ]; then
    echo "Reading variables from 'swakConfiguration'"
    source ./swakConfiguration
fi

(cd Libraries; ./Allwclean )

(cd Utilities; ./Allwclean )

# (cd Examples/tests/fluIntegration/libRegistered; wclean)
