#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp $FOAM_TUTORIALS/incompressible/simpleFoam/motorBike/constant/triSurface/motorBike.stl constant/triSurface/motorBike.stl

cp system/fvSolution.org system/fvSolution
cp -r 0.org 0 > /dev/null 2>&1

runApplication blockMesh
runApplication snappyHexMesh -overwrite

sed -i 's/\(nNonOrthogonalCorrectors\).*;/\1 10;/g' system/fvSolution
runApplication potentialFoam -writep
sed -i 's/\(nNonOrthogonalCorrectors\).*;/\1 0;/g' system/fvSolution

runApplication simpleFoam
