#! /bin/bash

wclean funkySetFields

wclean funkySetBoundaryField

wclean replayTransientBC

wclean funkySetAreaFields

wclean funkyDoCalc

wclean calcNonUniformOffsetsForMapped

wclean fieldReport

wclean funkyPythonPostproc

wclean funkySetLagrangianField

wclean funkyWarpMesh

wclean makeAxialMesh
