#! /bin/sh

if [ -d simpleFunctionObjects ]; then
    wclean simpleFunctionObjects
fi

wclean swak4FoamParsers

rm -f swak4FoamParsers/foamVersion4swak.H

# otherwise the next compilation will have trouble finding the version-file
find . -name lnInclude -exec rm -r {} \; -prune

wclean swakLagrangianParser

wclean groovyBC

wclean swakFunctionObjects

wclean simpleSwakFunctionObjects

wclean simpleLagrangianFunctionObjects

wclean simpleSearchableSurfaces

wclean swakTopoSources

wclean swakSourceFields

wclean swakFiniteArea

wclean groovyStandardBCs

wclean swakPythonIntegration

wclean swakFvOptions

(cd functionPlugins; ./Allwclean)

wclean simpleCloudFunctionObjects

wclean swakCloudFunctionObjects

# Remove residual from bison
rm -f */*.output

if [ "$SWAK_USER_PLUGINS" != "" ]
then
    plugins=$(echo $SWAK_USER_PLUGINS | tr ";" "\n")

    for plug in $plugins
    do
	echo "Clearing user function-plugin $plug"
	wclean $plugins
    done
fi
