#! /bin/sh

(export WM_NCOMPPROCS= ; wmake libso swak4FoamParsers)

wmake libso groovyBC

wmake libso swakFunctionObjects

wmake libso simpleSwakFunctionObjects

wmake libso swakTopoSources

wmake libso swakSourceFields

if [ "$FOAM_DEV" != "" ]
then
    (export WM_NCOMPPROCS= ; wmake libso swakFiniteArea)
fi

wmake libso groovyStandardBCs
