#! /bin/sh

(export WM_NCOMPPROCS= ; wmake libso swak4FoamParsers)

wmake libso groovyBC

wmake libso swakFunctionObjects

wmake libso simpleSwakFunctionObjects

wmake libso swakTopoSources

wmake libso swakSourceFields
