#! /bin/bash

if [ "$SWAK_PYTHON2_INCLUDE" != "" ]; then
    wmake
else
    echo
    echo "SWAK_PYTHON2_INCLUDE not defined .... no Python-Integration. Utility funkyPythonPostproc not compiled"
    echo
    exit 0
fi
