// automatically generated by makeSwakVersionFile.py
#define SWAK_VERSION_STRING "0.3.1"
#define SWAK_VERSION_MAJOR 0
#define SWAK_VERSION_MINOR 3
#define SWAK_VERSION_PATCH 1
#define SWAK_RELEASE_DATE "2014-07-11"
