Document: swak4foam
Title: Debian swak4foam Manual
Author: <insert document author here>
Abstract: This manual describes what swak4foam is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/swak4foam/swak4foam.sgml.gz

Format: postscript
Files: /usr/share/doc/swak4foam/swak4foam.ps.gz

Format: text
Files: /usr/share/doc/swak4foam/swak4foam.text.gz

Format: HTML
Index: /usr/share/doc/swak4foam/html/index.html
Files: /usr/share/doc/swak4foam/html/*.html
