#! /bin/sh

if [ -e ../../swakConfiguration ]; then
    echo "Reading variables from 'swakConfiguration'"
    source ../../swakConfiguration
else
    echo "No file 'swakConfiguration' in the top directory of the swak-sources. Language integrations probably won't work"
fi

wmake libso swakGeneralLanguageIntegration

if [ "$SWAK_PYTHON2_INCLUDE" != "" ]
then
    SOEXT=so

    if [ `uname -s`=="Darwin" ]; then
	SOEXT=dylib
    fi

    oldPython="$FOAM_USER_LIBBIN/libpythonIntegration.$SOEXT"
    if [ -e $oldPython ]
    then
	echo "Removing old python integration $oldPython"
	rm $oldPython
    fi
    wmake libso swakPythonIntegration
else
    echo
    echo "SWAK_PYTHON2_INCLUDE not defined .... no Python-Integration. Most people are fine without it"
    echo
fi
