#! /bin/bash

wmake libso swakMeshQualityFunctionPlugin

wmake libso swakLocalCalculationsFunctionPlugin

wmake libso swakRandomFunctionPlugin

wmake libso swakFvcSchemesFunctionPlugin

wmake libso swakThermoTurbFunctionPlugin

wmake libso swakTransportTurbFunctionPlugin

wmake libso swakSurfacesAndSetsFunctionPlugin

wmake libso swakLagrangianCloudSourcesFunctionPlugin

wmake libso swakVelocityFunctionPlugin

wmake libso swakChemistryModelFunctionPlugin

wmake libso swakRadiationModelFunctionPlugin

if [ "$FOAM_DEV" != "" ]
then
    wmake libso swakFacSchemesFunctionPlugin
fi
