#! /bin/bash

for d in `ls | grep swak | grep FunctionPlugin`
do
    if [ "$d" != "swakFacSchemesFunctionPlugin" ]
    then
	wmake libso $d
    fi
done

if [[ "$FOAM_DEV" != "" || ( ${WM_PROJECT_VERSION:0:1} == "v" && ${WM_PROJECT_VERSION:1} -gt 1707 ) ]]
then
    wmake libso swakFacSchemesFunctionPlugin
fi

(cd lagrangianCloudAdaptors; ./Allwmake )
