#! /bin/bash

wmake libso swakMeshQualityFunctionPlugin

wmake libso swakLocalCalculationsFunctionPlugin

wmake libso swakRandomFunctionPlugin

wmake libso swakFvcSchemesFunctionPlugin

if [ "$FOAM_DEV" != "" ]
then
    wmake libso swakFacSchemesFunctionPlugin
fi
