#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication blockMesh
runApplication topoSet
runApplication setsToZones

# parallel run
#runApplication decomposePar
#runParallel $application 6

# serial run
runApplication $application

# ----------------------------------------------------------------- end-of-file
